### ISSUE TITLE
Id of the app is 'omeka' in the manifest, but the repo url is 'omeka-s_ynh' :| 

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/omeka-s_ynh#1]
ideally one or the other should be chosen, because many pieces of code in the project assume that the url ends with {app_id}_ynh

Same thing for the id in the app list : https://github.com/YunoHost/apps/blob/master/apps.json#L2542 In particular, that's the reason why the app is level 6 ("Consider adding your app to the YunoHost-Apps organization to allow the community to contribute more easily" - because there's a mismatch for the id)

**Comment by ericgaspar** [comment]
There is two flavor for this app: Omeka S and Omeka Classic. I changed the adress to avoid confusion but forgot the app-id... Thanks for pointing this out.
Should be fixed with https://github.com/YunoHost/apps/pull/1214 and #2
